json.total_bill @promoter_billing_calculator.total_bill
json.events_counter @promoter_billing_calculator.events_counter
json.offers_counter @promoter_billing_calculator.offers_counter
json.offers_bill @promoter_billing_calculator.offers_bill
json.events_bill @promoter_billing_calculator.events_bill
json.total_usage_in_hours @promoter_billing_calculator.total_usage_in_hours
json.account_created_at current_user.created_at
